spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:    #开发环境
    name: center-config-tx-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: center-config-tx-test
